CREATE DATABASE Clinic_db;
USE Clinic_db;

CREATE TABLE Patients
(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Dni VARCHAR(30) NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50),
	[Status] BIT DEFAULT 1
)

CREATE TABLE [Services]
(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	[Name] VARCHAR(30) NOT NULL,
	[Status] BIT DEFAULT 1 NOT NULL
)


CREATE TABLE Dates
(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdPatient UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Patients(Id) NOT NULL,
	IdService UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Services](Id) NOT NULL,
	DateService DATETIME NOT NULL,
	[Description] VARCHAR(500),
	[Status] BIT DEFAULT 1 NOT NULL
)

CREATE TABLE Users
(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	UserName VARCHAR(10),
	[PassWord] VARCHAR(32),
	Status BIT DEFAULT 1
)

INSERT INTO [Services] (Name) VALUES ('Medicina general'),('Odontología'),('Pediatria'),('Neurología');
INSERT INTO Users (UserName,PassWord) VALUES ('Jose','123456');